#! /bin/sh

####################################
# autostart
####################################

# hotkeys daemon
sxhkd &

# notification daemon
dunst &

# low battery notification
ps -aux | grep battery_popup.sh | grep -v grep | awk '{ print $2 }' | xargs kill -9
~/.config/scripts/battery_popup.sh -L 80 -d 5 -t 1m &

# shadows and smooth workspace switching
picom --backend xrender -cCGfb -o 1 -I 0.04 -O 0.04 -D 7 --config /dev/null

# change language on caps lock
setxkbmap -model pc104 -layout us,ru -variant ,, -option grp:caps_toggle

# dynamic wallpapers
dwall -s exodus
#~/.config/scripts/dynamic_wallpaper.sh /usr/share/wallpapers/Island/

# polybar
~/.config/polybar/launch.sh &

# Disable ugly cursor when hovering over background
xsetroot -cursor_name left_ptr

####################################
# bspwm settings
####################################
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config window_gap 12

bspc config top_padding 36
bspc config bottom_padding 12
bspc config left_padding 12
bspc config right_padding 12

bspc config top_monocle_padding 12
bspc config bottom_monocle_padding 12
bspc config left_monocle_padding 12
bspc config right_monocle_padding 12

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false

bspc config focused_border_color "#7c6f64"
bspc config normal_border_color "#282828"

bspc config focus_follows_pointer true

bspc rule -a skypeforlinux state=tiled

