#! /bin/sh

####################################
# autostart
####################################

# hotkeys daemon
sxhkd &

# notification daemon
dunst &

# color temperature adjuster
#redshift &

# low battery notification
ps -aux | grep battery_popup.sh | grep -v grep | awk '{ print $2 }' | xargs kill -9
~/.config/scripts/battery_popup.sh -L 20 -d 1 -t 1m &

# shadows and smooth workspace switching
picom --experimental-backends --config ~/.config/picom/picom.conf &

# change language on caps lock
setxkbmap -model pc104 -layout us,ru -variant ,, -option grp:caps_toggle

# dynamic wallpapers
feh --bg-scale /usr/share/wallpapers/sea.jpg

# polybar
~/.config/polybar/launch.sh &

# Disable ugly cursor when hovering over background
xsetroot -cursor_name left_ptr &

# Fix displaying Java applications
wmname LG3D &

####################################
# bspwm settings
####################################
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 12

bspc config top_padding 36
bspc config bottom_padding 12
bspc config left_padding 12
bspc config right_padding 12

bspc config top_monocle_padding 12
bspc config bottom_monocle_padding 12
bspc config left_monocle_padding 12
bspc config right_monocle_padding 12

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle true
#bspc config paddingless_monocle true
bspc config single_monocle false

bspc config focused_border_color "#7c6f64"
bspc config normal_border_color "#282828"
bspc config presel_feedback_color "#83a598"

bspc config focus_follows_pointer true

bspc rule -a Skype state=tiled

bspc config external_rules_command "/home/kamil/.config/bspwm/external_rules"
export _JAVA_AWT_WM_NONREPARENTING=1

